"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-21 09:36:14.527462
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

UPDATED_AT_TABLES = (
    "app_setting",
    "audit_log",
    "calendar_event",
    "calendar_source",
    "entry",
    "message",
    "note",
    "note_item",
    "session",
    "subscription",
    "task",
    "task_item",
    "tracker",
    "tracker_group",
)


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_setting",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_setting")),
        sa.UniqueConstraint("key", name="uq_app_setting_key"),
        schema="microsched",
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("trace_id", sa.UUID(), nullable=False),
        sa.Column("turn_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("tool", sa.Text(), nullable=True),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(entity_type IS NULL) = (entity_id IS NULL)",
            name=op.f("ck_audit_log_entity_reference_complete"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        schema="microsched",
    )
    op.create_index(
        "ix_audit_log_trace_id", "audit_log", ["trace_id"], unique=False, schema="microsched"
    )
    op.create_index(
        "ix_audit_log_turn_id", "audit_log", ["turn_id"], unique=False, schema="microsched"
    )
    op.create_table(
        "calendar_source",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('ics', 'excel', 'manual')", name=op.f("ck_calendar_source_kind_values")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_source")),
        schema="microsched",
    )
    op.create_index(
        "uq_calendar_source_name_lower",
        "calendar_source",
        [sa.literal_column("lower(name)")],
        unique=True,
        schema="microsched",
    )
    op.create_table(
        "message",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_private", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("trace_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("content LIKE 'enc:v1:%'", name=op.f("ck_message_content_ciphertext")),
        sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f("ck_message_role_values")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message")),
        schema="microsched",
    )
    op.create_index(
        "ix_message_trace_id", "message", ["trace_id"], unique=False, schema="microsched"
    )
    op.create_table(
        "note",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
        sa.Column("is_private", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT is_private OR body_md LIKE 'enc:v1:%'",
            name=op.f("ck_note_private_body_ciphertext"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note")),
        schema="microsched",
    )
    op.create_table(
        "session",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("user_email", sa.Text(), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("private_until", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
        sa.UniqueConstraint("token_hash", name="uq_session_token_hash"),
        schema="microsched",
    )
    op.create_table(
        "task",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("priority", sa.Text(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_private", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT is_private OR (title LIKE 'enc:v1:%' AND body_md LIKE 'enc:v1:%')",
            name=op.f("ck_task_private_ciphertext"),
        ),
        sa.CheckConstraint(
            "priority IS NULL OR priority IN ('p1', 'p2', 'p3')",
            name=op.f("ck_task_priority_values"),
        ),
        sa.CheckConstraint("status IN ('open', 'completed')", name=op.f("ck_task_status_values")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task")),
        schema="microsched",
    )
    op.create_index("ix_task_due_at", "task", ["due_at"], unique=False, schema="microsched")
    op.create_table(
        "tracker_group",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('health', 'finance')", name=op.f("ck_tracker_group_kind_values")
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_tracker_group_position_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracker_group")),
        sa.UniqueConstraint("id", "kind", name="uq_tracker_group_id_kind"),
        schema="microsched",
    )
    op.create_index(
        "uq_tracker_group_name_lower",
        "tracker_group",
        [sa.literal_column("lower(name)")],
        unique=True,
        schema="microsched",
    )
    op.create_table(
        "calendar_event",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_calendar_event_positive_duration")),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["microsched.calendar_source.id"],
            name=op.f("fk_calendar_event_source_id_calendar_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_event")),
        schema="microsched",
    )
    op.create_index(
        "ix_calendar_event_source_id",
        "calendar_event",
        ["source_id"],
        unique=False,
        schema="microsched",
    )
    op.create_index(
        "ix_calendar_event_starts_at",
        "calendar_event",
        ["starts_at"],
        unique=False,
        schema="microsched",
    )
    op.create_table(
        "note_item",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_note_item_position_nonnegative")),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["microsched.note.id"],
            name=op.f("fk_note_item_note_id_note"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note_item")),
        schema="microsched",
    )
    op.create_index(
        "ix_note_item_note_id", "note_item", ["note_id"], unique=False, schema="microsched"
    )
    op.create_table(
        "task_item",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_task_item_position_nonnegative")),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["microsched.task.id"],
            name=op.f("fk_task_item_task_id_task"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_item")),
        schema="microsched",
    )
    op.create_index(
        "ix_task_item_task_id", "task_item", ["task_id"], unique=False, schema="microsched"
    )
    op.create_table(
        "tracker",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("direction", sa.Text(), server_default=sa.text("'out'"), nullable=False),
        sa.Column("input_mode", sa.Text(), server_default=sa.text("'event'"), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column("reminder_time", sa.Time(), nullable=True),
        sa.Column("reminder_text", sa.Text(), nullable=True),
        sa.Column("is_private", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(input_mode = 'quantity' AND unit IS NOT NULL) OR "
            "(input_mode <> 'quantity' AND unit IS NULL)",
            name=op.f("ck_tracker_unit_matches_input_mode"),
        ),
        sa.CheckConstraint("direction IN ('in', 'out')", name=op.f("ck_tracker_direction_values")),
        sa.CheckConstraint(
            "input_mode IN ('event', 'money', 'quantity')",
            name=op.f("ck_tracker_input_mode_values"),
        ),
        sa.CheckConstraint("kind IN ('health', 'finance')", name=op.f("ck_tracker_kind_values")),
        sa.CheckConstraint("name LIKE 'enc:v1:%'", name=op.f("ck_tracker_name_ciphertext")),
        sa.ForeignKeyConstraint(
            ["group_id", "kind"],
            ["microsched.tracker_group.id", "microsched.tracker_group.kind"],
            name="fk_tracker_group_kind",
            ondelete="SET NULL (group_id)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracker")),
        schema="microsched",
    )
    op.create_index(
        "ix_tracker_group_id", "tracker", ["group_id"], unique=False, schema="microsched"
    )
    op.create_table(
        "subscription",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("tracker_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Text(), nullable=False),
        sa.Column("list_amount", sa.Text(), nullable=True),
        sa.Column("period_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("period_unit", sa.Text(), server_default=sa.text("'month'"), nullable=False),
        sa.Column("started_on", sa.Date(), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note_md", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "amount LIKE 'enc:v1:%'", name=op.f("ck_subscription_amount_ciphertext")
        ),
        sa.CheckConstraint(
            "list_amount IS NULL OR list_amount LIKE 'enc:v1:%'",
            name=op.f("ck_subscription_list_amount_ciphertext"),
        ),
        sa.CheckConstraint("name LIKE 'enc:v1:%'", name=op.f("ck_subscription_name_ciphertext")),
        sa.CheckConstraint(
            "period_unit IN ('day', 'week', 'month', 'year')",
            name=op.f("ck_subscription_period_unit_values"),
        ),
        sa.CheckConstraint("expires_on >= started_on", name=op.f("ck_subscription_date_order")),
        sa.CheckConstraint("period_count > 0", name=op.f("ck_subscription_period_count_positive")),
        sa.ForeignKeyConstraint(
            ["tracker_id"],
            ["microsched.tracker.id"],
            name=op.f("fk_subscription_tracker_id_tracker"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription")),
        schema="microsched",
    )
    op.create_index(
        "ix_subscription_expires_on",
        "subscription",
        ["expires_on"],
        unique=False,
        schema="microsched",
    )
    op.create_index(
        "ix_subscription_tracker_id",
        "subscription",
        ["tracker_id"],
        unique=False,
        schema="microsched",
    )
    op.create_table(
        "entry",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tracker_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("amount", sa.Text(), nullable=True),
        sa.Column("list_amount", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note_md", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "amount IS NULL OR amount LIKE 'enc:v1:%'", name=op.f("ck_entry_amount_ciphertext")
        ),
        sa.CheckConstraint(
            "list_amount IS NULL OR list_amount LIKE 'enc:v1:%'",
            name=op.f("ck_entry_list_amount_ciphertext"),
        ),
        sa.CheckConstraint(
            "note_md IS NULL OR note_md LIKE 'enc:v1:%'", name=op.f("ck_entry_note_ciphertext")
        ),
        sa.CheckConstraint(
            "quantity IS NULL OR quantity > 0", name=op.f("ck_entry_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["microsched.subscription.id"],
            name=op.f("fk_entry_subscription_id_subscription"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tracker_id"],
            ["microsched.tracker.id"],
            name=op.f("fk_entry_tracker_id_tracker"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entry")),
        schema="microsched",
    )
    op.create_index(
        "ix_entry_occurred_at", "entry", ["occurred_at"], unique=False, schema="microsched"
    )
    op.create_index(
        "ix_entry_subscription_id", "entry", ["subscription_id"], unique=False, schema="microsched"
    )
    op.create_index(
        "ix_entry_tracker_occurred_at",
        "entry",
        ["tracker_id", sa.literal_column("occurred_at DESC")],
        unique=False,
        schema="microsched",
    )
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION microsched.set_updated_at()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$
        """
    )
    for table_name in UPDATED_AT_TABLES:
        op.execute(
            f"CREATE TRIGGER set_updated_at "
            f"BEFORE UPDATE ON microsched.{table_name} "
            f"FOR EACH ROW EXECUTE FUNCTION microsched.set_updated_at()"
        )
    op.execute("REVOKE ALL ON TABLE microsched.alembic_version FROM microsched_app")


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_entry_tracker_occurred_at", table_name="entry", schema="microsched")
    op.drop_index("ix_entry_subscription_id", table_name="entry", schema="microsched")
    op.drop_index("ix_entry_occurred_at", table_name="entry", schema="microsched")
    op.drop_table("entry", schema="microsched")
    op.drop_index("ix_subscription_tracker_id", table_name="subscription", schema="microsched")
    op.drop_index("ix_subscription_expires_on", table_name="subscription", schema="microsched")
    op.drop_table("subscription", schema="microsched")
    op.drop_index("ix_tracker_group_id", table_name="tracker", schema="microsched")
    op.drop_table("tracker", schema="microsched")
    op.drop_index("ix_task_item_task_id", table_name="task_item", schema="microsched")
    op.drop_table("task_item", schema="microsched")
    op.drop_index("ix_note_item_note_id", table_name="note_item", schema="microsched")
    op.drop_table("note_item", schema="microsched")
    op.drop_index("ix_calendar_event_starts_at", table_name="calendar_event", schema="microsched")
    op.drop_index("ix_calendar_event_source_id", table_name="calendar_event", schema="microsched")
    op.drop_table("calendar_event", schema="microsched")
    op.drop_index("uq_tracker_group_name_lower", table_name="tracker_group", schema="microsched")
    op.drop_table("tracker_group", schema="microsched")
    op.drop_index("ix_task_due_at", table_name="task", schema="microsched")
    op.drop_table("task", schema="microsched")
    op.drop_table("session", schema="microsched")
    op.drop_table("note", schema="microsched")
    op.drop_index("ix_message_trace_id", table_name="message", schema="microsched")
    op.drop_table("message", schema="microsched")
    op.drop_index(
        "uq_calendar_source_name_lower", table_name="calendar_source", schema="microsched"
    )
    op.drop_table("calendar_source", schema="microsched")
    op.drop_index("ix_audit_log_turn_id", table_name="audit_log", schema="microsched")
    op.drop_index("ix_audit_log_trace_id", table_name="audit_log", schema="microsched")
    op.drop_table("audit_log", schema="microsched")
    op.drop_table("app_setting", schema="microsched")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION microsched.set_updated_at()")
